GET http://localhost:5000/questions
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjFiYjdhYjlhLTkzOGUtNDY4OS1hOThmLTY0OTM3OWE2MTQ2YiIsImlhdCI6MTY3MTAxODU4MSwiZXhwIjoxNjcxMDI4NTgxfQ.__GLmY8doQkVMzlcjW2EXyDkO6aQmKufEH0YqKB9jis

###
GET http://localhost:5000/questions/user/created
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjFiYjdhYjlhLTkzOGUtNDY4OS1hOThmLTY0OTM3OWE2MTQ2YiIsImlhdCI6MTY3MTAxODU4MSwiZXhwIjoxNjcxMDI4NTgxfQ.__GLmY8doQkVMzlcjW2EXyDkO6aQmKufEH0YqKB9jis

###
GET http://localhost:5000/questions/3f0c6cf0-808b-4c15-be88-d2bb1da3a64c
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjFiYjdhYjlhLTkzOGUtNDY4OS1hOThmLTY0OTM3OWE2MTQ2YiIsImlhdCI6MTY3MTAxODU4MSwiZXhwIjoxNjcxMDI4NTgxfQ.__GLmY8doQkVMzlcjW2EXyDkO6aQmKufEH0YqKB9jis

###
POST http://localhost:5000/questions
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjFiYjdhYjlhLTkzOGUtNDY4OS1hOThmLTY0OTM3OWE2MTQ2YiIsImlhdCI6MTY3MTAxODU4MSwiZXhwIjoxNjcxMDI4NTgxfQ.__GLmY8doQkVMzlcjW2EXyDkO6aQmKufEH0YqKB9jis
Content-Type: application/json

{
 
  "title": "What is javascript",
   "question":"I came across javascript while learning web what is it",
   "tags":"javascript"
}

###
PUT http://localhost:5000/questions/80870242-17f6-40e0-89af-8c360cf4b709
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjFiYjdhYjlhLTkzOGUtNDY4OS1hOThmLTY0OTM3OWE2MTQ2YiIsImlhdCI6MTY3MTAxODU4MSwiZXhwIjoxNjcxMDI4NTgxfQ.__GLmY8doQkVMzlcjW2EXyDkO6aQmKufEH0YqKB9jis
Content-Type: application/json

{
  
    "title": "What is javascript",
   "question":"I came across javascript while learning web what is it",
   "tags":"javascript, programming"
}

###
DELETE http://localhost:5000/questions/0b735990-0996-4bec-a195-f6313e33685e
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjFiYjdhYjlhLTkzOGUtNDY4OS1hOThmLTY0OTM3OWE2MTQ2YiIsImlhdCI6MTY3MTAxODU4MSwiZXhwIjoxNjcxMDI4NTgxfQ.__GLmY8doQkVMzlcjW2EXyDkO6aQmKufEH0YqKB9jis


###
POST http://localhost:5000/questions/answer/add
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjFiYjdhYjlhLTkzOGUtNDY4OS1hOThmLTY0OTM3OWE2MTQ2YiIsImlhdCI6MTY3MTAxODU4MSwiZXhwIjoxNjcxMDI4NTgxfQ.__GLmY8doQkVMzlcjW2EXyDkO6aQmKufEH0YqKB9jis
Content-Type: application/json

{
 
   "question_id":"3f0c6cf0-808b-4c15-be88-d2bb1da3a64c",
   "answer":"Javascript is a programming language"
   
}



###
PUT http://localhost:5000/questions/answer/preffered
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjFiYjdhYjlhLTkzOGUtNDY4OS1hOThmLTY0OTM3OWE2MTQ2YiIsImlhdCI6MTY3MTAxODU4MSwiZXhwIjoxNjcxMDI4NTgxfQ.__GLmY8doQkVMzlcjW2EXyDkO6aQmKufEH0YqKB9jis
Content-Type: application/json

{
"id":"007227e8-a4a7-45be-945a-3799a6f770fb"
}

###
PUT http://localhost:5000/questions/answer/unprefer
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjFiYjdhYjlhLTkzOGUtNDY4OS1hOThmLTY0OTM3OWE2MTQ2YiIsImlhdCI6MTY3MTAxODU4MSwiZXhwIjoxNjcxMDI4NTgxfQ.__GLmY8doQkVMzlcjW2EXyDkO6aQmKufEH0YqKB9jis
Content-Type: application/json

{
"id":"007227e8-a4a7-45be-945a-3799a6f770fb"
}

###
DELETE http://localhost:5000/questions/answer/delete/d90efae9-cc88-48d6-ab6a-d92bc6849c53
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjFiYjdhYjlhLTkzOGUtNDY4OS1hOThmLTY0OTM3OWE2MTQ2YiIsImlhdCI6MTY3MTAxODU4MSwiZXhwIjoxNjcxMDI4NTgxfQ.__GLmY8doQkVMzlcjW2EXyDkO6aQmKufEH0YqKB9jis

###
POST http://localhost:5000/questions/answer/comment
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjFiYjdhYjlhLTkzOGUtNDY4OS1hOThmLTY0OTM3OWE2MTQ2YiIsImlhdCI6MTY3MTAxODU4MSwiZXhwIjoxNjcxMDI4NTgxfQ.__GLmY8doQkVMzlcjW2EXyDkO6aQmKufEH0YqKB9jis
Content-Type: application/json

{   
   "answer_id":"007227e8-a4a7-45be-945a-3799a6f770fb",
   "comment":"Yes sure it is a programming language"
}

###
DELETE   http://localhost:5000/questions/comment/d90efae9-cc88-48d6-ab6a-d92bc6849c53
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjFiYjdhYjlhLTkzOGUtNDY4OS1hOThmLTY0OTM3OWE2MTQ2YiIsImlhdCI6MTY3MTAxODU4MSwiZXhwIjoxNjcxMDI4NTgxfQ.__GLmY8doQkVMzlcjW2EXyDkO6aQmKufEH0YqKB9jis




###
GET  http://localhost:5000/questions/ordered/top
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjFiYjdhYjlhLTkzOGUtNDY4OS1hOThmLTY0OTM3OWE2MTQ2YiIsImlhdCI6MTY3MTAxODU4MSwiZXhwIjoxNjcxMDI4NTgxfQ.__GLmY8doQkVMzlcjW2EXyDkO6aQmKufEH0YqKB9jis

###
POST   http://localhost:5000/questions/list/search
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjFiYjdhYjlhLTkzOGUtNDY4OS1hOThmLTY0OTM3OWE2MTQ2YiIsImlhdCI6MTY3MTAxODU4MSwiZXhwIjoxNjcxMDI4NTgxfQ.__GLmY8doQkVMzlcjW2EXyDkO6aQmKufEH0YqKB9jis
Content-Type: application/json

{
   "searchTerm": "javascript"
}



###
POST http://localhost:5000/questions/answer/upvote
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjFiYjdhYjlhLTkzOGUtNDY4OS1hOThmLTY0OTM3OWE2MTQ2YiIsImlhdCI6MTY3MTAxODU4MSwiZXhwIjoxNjcxMDI4NTgxfQ.__GLmY8doQkVMzlcjW2EXyDkO6aQmKufEH0YqKB9jis
Content-Type: application/json

{
   "answer_id":"007227e8-a4a7-45be-945a-3799a6f770fb"
}

###
POST http://localhost:5000/questions/answer/downvote
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjFiYjdhYjlhLTkzOGUtNDY4OS1hOThmLTY0OTM3OWE2MTQ2YiIsImlhdCI6MTY3MTAxODU4MSwiZXhwIjoxNjcxMDI4NTgxfQ.__GLmY8doQkVMzlcjW2EXyDkO6aQmKufEH0YqKB9jis
Content-Type: application/json

{
   "answer_id":"007227e8-a4a7-45be-945a-3799a6f770fb"
}