GET http://localhost:5000/questions
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjQwM2M2ZTZmLTgxOGItNDJlOS1hNmRlLWNjMTE5YmUwMTRkNyIsImVtYWlsIjoiamFuZWRAZ21haWwuY29tIiwidXNlcm5hbWUiOiJKYW5lRCIsImlhdCI6MTY3MDkyMjcyNiwiZXhwIjoxNjcwOTMyNzI2fQ.OhzM7De98QX9cMoTX3L4AI39O22a1g0Fhruz3UCsmrw

###
GET http://localhost:5000/questions/user/created
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjQwM2M2ZTZmLTgxOGItNDJlOS1hNmRlLWNjMTE5YmUwMTRkNyIsImVtYWlsIjoiamFuZWRAZ21haWwuY29tIiwidXNlcm5hbWUiOiJKYW5lRCIsImlhdCI6MTY3MDkyMjcyNiwiZXhwIjoxNjcwOTMyNzI2fQ.OhzM7De98QX9cMoTX3L4AI39O22a1g0Fhruz3UCsmrw

###
GET http://localhost:5000/questions/cec0b7ec-d5d7-421e-8ac7-44ccebaa52fe
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjQwM2M2ZTZmLTgxOGItNDJlOS1hNmRlLWNjMTE5YmUwMTRkNyIsImVtYWlsIjoiamFuZWRAZ21haWwuY29tIiwidXNlcm5hbWUiOiJKYW5lRCIsImlhdCI6MTY3MDkyMjcyNiwiZXhwIjoxNjcwOTMyNzI2fQ.OhzM7De98QX9cMoTX3L4AI39O22a1g0Fhruz3UCsmrw

###
POST http://localhost:5000/questions
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjQwM2M2ZTZmLTgxOGItNDJlOS1hNmRlLWNjMTE5YmUwMTRkNyIsImVtYWlsIjoiamFuZWRAZ21haWwuY29tIiwidXNlcm5hbWUiOiJKYW5lRCIsImlhdCI6MTY3MDkyMjcyNiwiZXhwIjoxNjcwOTMyNzI2fQ.OhzM7De98QX9cMoTX3L4AI39O22a1g0Fhruz3UCsmrw
Content-Type: application/json

{
 
  "title": "What is OS",
   "question":"What does OS mean in nodejs",
   "tags":"node"
}

###
PUT http://localhost:5000/questions/24eff609-7b18-4189-9d0a-2375e454b49a
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjQwM2M2ZTZmLTgxOGItNDJlOS1hNmRlLWNjMTE5YmUwMTRkNyIsImVtYWlsIjoiamFuZWRAZ21haWwuY29tIiwidXNlcm5hbWUiOiJKYW5lRCIsImlhdCI6MTY3MDkyMjcyNiwiZXhwIjoxNjcwOTMyNzI2fQ.OhzM7De98QX9cMoTX3L4AI39O22a1g0Fhruz3UCsmrw
Content-Type: application/json

{
  
   "title": "What is Os",
   "question":"What is Os, what does it mean",
   "tags":"node, tech"
}

###
DELETE http://localhost:5000/questions/24eff609-7b18-4189-9d0a-2375e454b49a
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjQwM2M2ZTZmLTgxOGItNDJlOS1hNmRlLWNjMTE5YmUwMTRkNyIsImVtYWlsIjoiamFuZWRAZ21haWwuY29tIiwidXNlcm5hbWUiOiJKYW5lRCIsImlhdCI6MTY3MDkyMjcyNiwiZXhwIjoxNjcwOTMyNzI2fQ.OhzM7De98QX9cMoTX3L4AI39O22a1g0Fhruz3UCsmrw


###
POST http://localhost:5000/questions/answer/add
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjQwM2M2ZTZmLTgxOGItNDJlOS1hNmRlLWNjMTE5YmUwMTRkNyIsImVtYWlsIjoiamFuZWRAZ21haWwuY29tIiwidXNlcm5hbWUiOiJKYW5lRCIsImlhdCI6MTY3MDkyMjcyNiwiZXhwIjoxNjcwOTMyNzI2fQ.OhzM7De98QX9cMoTX3L4AI39O22a1g0Fhruz3UCsmrw
Content-Type: application/json

{
 
   "question_id":"cec0b7ec-d5d7-421e-8ac7-44ccebaa52fe",
   "answer":"Operating system "
   
}



###
PUT http://localhost:5000/questions/answer/preffered
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjQwM2M2ZTZmLTgxOGItNDJlOS1hNmRlLWNjMTE5YmUwMTRkNyIsImVtYWlsIjoiamFuZWRAZ21haWwuY29tIiwidXNlcm5hbWUiOiJKYW5lRCIsImlhdCI6MTY3MDkyMjcyNiwiZXhwIjoxNjcwOTMyNzI2fQ.OhzM7De98QX9cMoTX3L4AI39O22a1g0Fhruz3UCsmrw
Content-Type: application/json

{
"id":"e0003a45-546c-4eb3-b414-c7296de123e8"
}

###
PUT http://localhost:5000/questions/answer/unprefer
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjQwM2M2ZTZmLTgxOGItNDJlOS1hNmRlLWNjMTE5YmUwMTRkNyIsImVtYWlsIjoiamFuZWRAZ21haWwuY29tIiwidXNlcm5hbWUiOiJKYW5lRCIsImlhdCI6MTY3MDkyMjcyNiwiZXhwIjoxNjcwOTMyNzI2fQ.OhzM7De98QX9cMoTX3L4AI39O22a1g0Fhruz3UCsmrw
Content-Type: application/json

{
"id":"e0003a45-546c-4eb3-b414-c7296de123e8"
}

###
DELETE http://localhost:5000/questions/answer/delete/d90efae9-cc88-48d6-ab6a-d92bc6849c53
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjQwM2M2ZTZmLTgxOGItNDJlOS1hNmRlLWNjMTE5YmUwMTRkNyIsImVtYWlsIjoiamFuZWRAZ21haWwuY29tIiwidXNlcm5hbWUiOiJKYW5lRCIsImlhdCI6MTY3MDkyMjcyNiwiZXhwIjoxNjcwOTMyNzI2fQ.OhzM7De98QX9cMoTX3L4AI39O22a1g0Fhruz3UCsmrw

###
POST http://localhost:5000/questions/answer/comment
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjQwM2M2ZTZmLTgxOGItNDJlOS1hNmRlLWNjMTE5YmUwMTRkNyIsImVtYWlsIjoiamFuZWRAZ21haWwuY29tIiwidXNlcm5hbWUiOiJKYW5lRCIsImlhdCI6MTY3MDkyMjcyNiwiZXhwIjoxNjcwOTMyNzI2fQ.OhzM7De98QX9cMoTX3L4AI39O22a1g0Fhruz3UCsmrw
Content-Type: application/json

{   
   "answer_id":"e0003a45-546c-4eb3-b414-c7296de123e8",
   "comment":"It is also a unit in computer science"
}

###
DELETE   http://localhost:5000/questions/comment/d90efae9-cc88-48d6-ab6a-d92bc6849c53
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjQwM2M2ZTZmLTgxOGItNDJlOS1hNmRlLWNjMTE5YmUwMTRkNyIsImVtYWlsIjoiamFuZWRAZ21haWwuY29tIiwidXNlcm5hbWUiOiJKYW5lRCIsImlhdCI6MTY3MDkyMjcyNiwiZXhwIjoxNjcwOTMyNzI2fQ.OhzM7De98QX9cMoTX3L4AI39O22a1g0Fhruz3UCsmrw

###
POST http://localhost:5000/questions/answer/upvote
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjQwM2M2ZTZmLTgxOGItNDJlOS1hNmRlLWNjMTE5YmUwMTRkNyIsImVtYWlsIjoiamFuZWRAZ21haWwuY29tIiwidXNlcm5hbWUiOiJKYW5lRCIsImlhdCI6MTY3MDkyMjcyNiwiZXhwIjoxNjcwOTMyNzI2fQ.OhzM7De98QX9cMoTX3L4AI39O22a1g0Fhruz3UCsmrw
Content-Type: application/json

{
   "answer_id":"0ad1dc34-fa98-4d5f-a20e-1126b8b19e67"
}


###
POST http://localhost:5000/questions/answer/downvote
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjQwM2M2ZTZmLTgxOGItNDJlOS1hNmRlLWNjMTE5YmUwMTRkNyIsImVtYWlsIjoiamFuZWRAZ21haWwuY29tIiwidXNlcm5hbWUiOiJKYW5lRCIsImlhdCI6MTY3MDkyMjcyNiwiZXhwIjoxNjcwOTMyNzI2fQ.OhzM7De98QX9cMoTX3L4AI39O22a1g0Fhruz3UCsmrw
Content-Type: application/json

{
   "answer_id":"adab94ed-f426-4bc7-8c45-b5a424bfbe04"
}


###
GET  http://localhost:5000/questions/ordered/top
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjQwM2M2ZTZmLTgxOGItNDJlOS1hNmRlLWNjMTE5YmUwMTRkNyIsImVtYWlsIjoiamFuZWRAZ21haWwuY29tIiwidXNlcm5hbWUiOiJKYW5lRCIsImlhdCI6MTY3MDkyMjcyNiwiZXhwIjoxNjcwOTMyNzI2fQ.OhzM7De98QX9cMoTX3L4AI39O22a1g0Fhruz3UCsmrw

###
POST   http://localhost:5000/questions/list/search
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjQwM2M2ZTZmLTgxOGItNDJlOS1hNmRlLWNjMTE5YmUwMTRkNyIsImVtYWlsIjoiamFuZWRAZ21haWwuY29tIiwidXNlcm5hbWUiOiJKYW5lRCIsImlhdCI6MTY3MDkyMjcyNiwiZXhwIjoxNjcwOTMyNzI2fQ.OhzM7De98QX9cMoTX3L4AI39O22a1g0Fhruz3UCsmrw
Content-Type: application/json

{
   "searchTerm": "chj"
}


/////////////test
###
POST http://localhost:5000/questions/answer/upvote
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjQwM2M2ZTZmLTgxOGItNDJlOS1hNmRlLWNjMTE5YmUwMTRkNyIsImVtYWlsIjoiamFuZWRAZ21haWwuY29tIiwidXNlcm5hbWUiOiJKYW5lRCIsImlhdCI6MTY3MDkyMjcyNiwiZXhwIjoxNjcwOTMyNzI2fQ.OhzM7De98QX9cMoTX3L4AI39O22a1g0Fhruz3UCsmrw
Content-Type: application/json

{
   "answer_id":"e0003a45-546c-4eb3-b414-c7296de123e8"
}

###
POST http://localhost:5000/questions/answer/downvote
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjQwM2M2ZTZmLTgxOGItNDJlOS1hNmRlLWNjMTE5YmUwMTRkNyIsImVtYWlsIjoiamFuZWRAZ21haWwuY29tIiwidXNlcm5hbWUiOiJKYW5lRCIsImlhdCI6MTY3MDkyMjcyNiwiZXhwIjoxNjcwOTMyNzI2fQ.OhzM7De98QX9cMoTX3L4AI39O22a1g0Fhruz3UCsmrw
Content-Type: application/json

{
   "answer_id":"e0003a45-546c-4eb3-b414-c7296de123e8"
}