
POST http://localhost:5001/user/signup
Content-Type: application/json

{
    "username":"Res",
    "email": "res@gmail.com",
    "password": "254Res254"
}

###
POST http://localhost:5001/user/login
Content-Type: application/json

{
     "email": "res@gmail.com",
    "password": "254Res254"
}