
POST http://localhost:5001/user/signup
Content-Type: application/json

{
    "username":"EricaWanja",
    "email": "ericawanja@gmail.com",
    "password": "254ericawanja254"
}

###
POST http://localhost:5001/user/login
Content-Type: application/json

{
     "email": "ericawanja@gmail.com",
    "password": "254ericawanja254"
}