
POST http://localhost:5001/user/signup
Content-Type: application/json

{
    "username":"JaneD",
    "email": "janed@gmail.com",
    "password": "254Jane254"
}

###
POST http://localhost:5001/user/login
Content-Type: application/json

{
     "email": "janed@gmail.com",
    "password": "254Jane254"
}